/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Cheese-grinder stencil Plugin.
 * It contains typing information for all configurable components that exist in this project.
 */
export interface ComponentOptions {
  "pop-drawer"?: {
    triggerAction?: "click" | "context-menu" | "hover";
    side?: "end" | "start";
    open?: boolean;
  }
}